version: 0.1.0-alpha001-{build}
configuration:
  - Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
  - appveyor-retry dotnet restore
build_script:
  - dotnet build "src\AspNetCore.Lambda" -c %CONFIGURATION% --no-dependencies --version-suffix %APPVEYOR_BUILD_ID%
test_script:
  - dotnet build "tests\AspNetCore.Lambda.Tests" -c %CONFIGURATION%
  - dotnet test "tests\AspNetCore.Lambda.Tests" -c %CONFIGURATION%
after_build:
  - dotnet pack "src\AspNetCore.Lambda" -c %CONFIGURATION% --no-build
artifacts:
  - path: '**\AspNetCore.Lambda.*.nupkg'
    name: AspNetCore.Lambda
nuget:
  account_feed: false
  project_feed: false